
# Create a list and just append whatever you want to it!

positive_sayings = list()
positive_sayings.append("You are a unique child of this world.")
positive_sayings.append("You have as much brightness to offer the world as the next person.")
positive_sayings.append("You matter and what you have to this world also matters.")
positive_sayings.append("Trust yourself.")
positive_sayings.append("The situation you're in will work out for your highest good.")
positive_sayings.append("Wonderful things will unfold before you.")
positive_sayings.append("Draw from your inner strength and light.")
positive_sayings.append("You may not make all the right choices, but you'll grow from all of them.")
positive_sayings.append("Feel the love from those not physically around you.")
positive_sayings.append("You are too big a gift to this world to feel self-pity.")
positive_sayings.append("I love and approve of you.")
positive_sayings.append("Forgive yourself for all the mistakes you've made. They've made you better.")
positive_sayings.append("Let go of your anger so you can see things clearly.")
positive_sayings.append("Accept responsibility if your anger has hurt anyone, and work to rememedy it.")
positive_sayings.append("Replace your anger with understanding and compassion.")
positive_sayings.append("You may not understand the good in this situation, but it is there, time will tell.")
positive_sayings.append("Muster up more hope and courage from deep inside you.")
positive_sayings.append("Choose to find hopeful and optimistic ways to look at your situation.")
positive_sayings.append("It's ok to ask for help and guidance - it's not weakness, it's intelligence.")
positive_sayings.append("Refuse to give up, there's always another way.")
positive_sayings.append("Never stop loving.")
positive_sayings.append("Receive all feedback with kindness, but ultimately you make the final call.")
positive_sayings.append("Continue showing love to everyone, it will come back to you.")
positive_sayings.append("You are a better person from all the pain you've gone through.")
positive_sayings.append("Choose friends who approve and love you.")
positive_sayings.append("Surround yourself with people who treat you well.")
positive_sayings.append("Take the time to show your friends that you care about them.")
positive_sayings.append("Take great pleasure with your friends, even if you disagree or live different lives.")
positive_sayings.append("You play a huge role in your own career success.")
positive_sayings.append("What you do is meaningful and rewarding.")
positive_sayings.append("Believe in your ability to change the world with the work that you do.")
positive_sayings.append("Engage in activities that impact this world positively.")
positive_sayings.append("Peaceful sleep awaits for you in the dreamland.")
positive_sayings.append("Let go of all the false stories that you make up in your head.")
positive_sayings.append("Release your mind of throught until you wake up.")
positive_sayings.append("Embrace the peace and quiet of the night.")
positive_sayings.append("The day will bring you nothing but growth.")
positive_sayings.append("Today will be a gorgeous day to remember.")
positive_sayings.append("Your thoughts are your reality so think up a bright new day.")
positive_sayings.append("Fill up your day with hope and face it with joy.")
positive_sayings.append("Choose to fully participate in your day.")
positive_sayings.append("Let go of worries that simply drain your energy.")
positive_sayings.append("You are a smart, caluclated person.")
positive_sayings.append("You are in complete charge of planning for your future.")
positive_sayings.append("Trust in your own abilities.")
positive_sayings.append("Follow your dreams no matter what.")
positive_sayings.append("If they don't support you, don't associate with them.")
positive_sayings.append("Pursue your dream.")
positive_sayings.append("All your problems have a solution. Find it")
positive_sayings.append("You are safe and sound. All is well.")
positive_sayings.append("There is a great reason this is unfolding before me now.")
positive_sayings.append("You have the smarts and the ability to get through this.")
positive_sayings.append("Seek a new way of thinking about your situation.")
positive_sayings.append("The answer is right before you, even if you can't see it yet.")
positive_sayings.append("Believe in your ability to unlock the way and set yourself free.")
positive_sayings.append("You have no right to compare yourself to anyone, for you do not know their whole story, nor them, yours.")
positive_sayings.append("Compare youself only to that of your highest self.")
positive_sayings.append("Choose to see the light that you are to this world.")
positive_sayings.append("Be happy in your own skin and in your own circumstances.")
positive_sayings.append("You are a gift to everyone who interacts with you.")
positive_sayings.append("You are more than good enough and you're getting better every day.")
positive_sayings.append("Adopt the mindset to praise yourself.")
positive_sayings.append("Give up that self-critical habit.")
positive_sayings.append("See the perfection in all your flaws and all your genius.")
positive_sayings.append("You ARE a good person at all times of day and night.")
positive_sayings.append("Bad thoughts do not make you a bad person.")
positive_sayings.append("We all struggle, it's ok, you're strong. I believe in you.")
positive_sayings.append("You cannot give up until you have tried every single possible conceivable way.")
positive_sayings.append("Giving up is easy and always an option, so let's delay it for another day.")
positive_sayings.append("Press on, your path is true.")
positive_sayings.append("It is always too early to give up on your goals.")
positive_sayings.append("You've already traversed so far through the dark tunnel, don't give up just yet.")
positive_sayings.append("The past has no power over you anymore.")
positive_sayings.append("Embrace the rhythm ad the flowing of your own heart.")
positive_sayings.append("All that you need comes to you at the right time and place in this life.")
positive_sayings.append("You should be deeply fulfilled with who you are.")